### ISSUE TITLE
Not displaying correct name 

### ISSUE THREAD

**Issue by TJBBROSS15** [MrCrayfish/GoldenHopper#1]
hello i just downloaded the awesome golden hopper mod but was noticing that it wasnt displaying the correct name from the hotbar or creative inventory or even the golden hoppers inventory. hopefully this helps fix it thanks :)
![2020-04-13_21 20 28](https://user-images.githubusercontent.com/63629197/79186006-553c3c00-7dcd-11ea-9a4d-a2fcdab6dece.png)
![2020-04-13_21 20 36](https://user-images.githubusercontent.com/63629197/79186035-62f1c180-7dcd-11ea-9f7d-4231c5549e3d.png)

**Comment by MrCrayfish** [comment]
It turns out I uploaded the wrong file. Simply download the mod again as I have fixed it
