### ISSUE TITLE
Placing a sink is crashing my game and deleting the whole chunk after.

### ISSUE THREAD

**Issue by Zaline99** [MrCrayfish/GoldenHopper#14]
Placing a sink is crashing my game, after a restart I find the whole chunk i placed the sink in deleted and invisible. I unfortunatly dont have a screenshot of it.

The same happened with a doormat to me a few days ago.

I do have the crash report if that helps

[crash-2022-01-30_13.41.30-server.txt](https://github.com/MrCrayfish/GoldenHopper/files/7965921/crash-2022-01-30_13.41.30-server.txt)

**Comment by MrCrayfish** [comment]
Updated to latest version
