### ISSUE TITLE
Broken textures on 1.18

### ISSUE THREAD

**Issue by InfernumYT** [MrCrayfish/GoldenHopper#15]
Textures are broken when hopper is pointing at any other direction than down
And pls make this hopper faster(8 ticks is default hopper speed, pls change it to 7 or 6 or do config file)

forge-39.0.63

**Comment by MrCrayfish** [comment]
Weird, I've not had that problem. Maybe Forge changed something since I would not miss such an obvious issue.

**Comment by MrCrayfish** [comment]
Closing as stale. If issue is still present  on 1.18.2 open a new issue.
