### ISSUE TITLE
Failed to load correctly error 1.18.x

### ISSUE THREAD

**Issue by Nalwyn603** [MrCrayfish/GoldenHopper#19]
I've been troubleshooting mods and found that no matter what version of GoldenHopper I use I get the error that the mod had failed to load correctly. I have tried both the newest and second newest version of Forge 1.18.2, and this was the only mod in the folder

**Comment by MrCrayfish** [comment]
It should work now. This was a breaking change in 1.18.2, the mod would work fine on 1.18.1
