### ISSUE TITLE
Cannot get property DirectionProperty crash error 

### ISSUE THREAD

**Issue by YukiRainee** [MrCrayfish/GoldenHopper#22]
Seem to be getting a crash when attempting to load the mod 

Heres the top line of the crash report `java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=from, clazz=class net.minecraft.core.Direction, values=[down, up, north, south, west, east]} as it does not exist in Block{goldenhopper:golden_hopper}`

[crash-2022-08-03_22.32.45-client.txt](https://github.com/MrCrayfish/GoldenHopper/files/9256914/crash-2022-08-03_22.32.45-client.txt)

**Comment by MrCrayfish** [comment]
Hopper Plus is breaking the mod since it overrides the vanilla hopper with custom code. Golden Hopper is based on vanilla code. Unfortunately Hopper Plus does not have anywhere to view their code or report issue.
