### ISSUE TITLE
Game Keeps crashing when trying to open

### ISSUE THREAD

**Issue by Leaf214321** [MrCrayfish/GoldenHopper#31]
After downloading the mod and the framework mod the game keeps crashing with the error code: "Error: java.lang.RuntimeException: null". The game works fine without the mods and will request the framework mod if it's not installed but won't open if it is installed,
[crash-2024-01-27_23.33.16-client.txt](https://github.com/MrCrayfish/GoldenHopper/files/14074957/crash-2024-01-27_23.33.16-client.txt)

**Comment by MrCrayfish** [comment]
The mod is not available for Minecraft 1.20.2
