### ISSUE TITLE
disfonctionnement 1.21

### ISSUE THREAD

**Issue by dides57** [MrCrayfish/GoldenHopper#34]
bonjour,
le mod ne fonctionne pas en 1.21, des que je mets l'item dans le filtre il tombe directement dans lentonnoir d'en dessous.

**Comment by MrCrayfish** [comment]
The golden hopper only filters items that are sucked in, not placed into the inventory slots

**Comment by dides57** [comment]
oui, mais je n'arrive mettre aucun objet dans le filtre pour pouvoir justement filtrer, si je place un entonnoir en dessous du goldenhopper, l'entonnoir aspire le filtre également. en 1.20 cela ne posait aucun probleme et donc je n'arrive plus faire de salle des coffres comme je l'avais fait
