### ISSUE TITLE
Crash Occurs When Interacting with or Placing Golden Hopper

### ISSUE THREAD

**Issue by Stickly10** [MrCrayfish/GoldenHopper#36]
Hi, I am facing the following crash:
![image](https://github.com/user-attachments/assets/cb74d1b5-fa2e-4da6-adf0-c416a71d9b90)

The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Invalid block entity minecraft:hopper // com.mrcrayfish.goldenhopper.blockentity.GoldenHopperBlockEntity state at BlockPos{x=-12, y=57, z=107}, got Block{goldenhopper:golden_hopper}[enabled=true,facing=down]

Minecraft Version: 1.21.1
Neoforge Version: 21.1.11
Mod Version: 1.5.3
Error Log: https://pastebin.com/sfLQYgQT

Context: It happens anytime I look at a golden hopper that is already placed in my world. Also, if I try to place a new golden hopper, I get the crash.

**Comment by MrCrayfish** [comment]
The mod has not been tested on 1.21.1 yet. Even though it can run, I would uninstall it until I release a version that has been verified by myself.

**Comment by Stickly10** [comment]
Thank you so much for your response, the mod was working good on previus Neoforge's Versions, so i will go back on previus version, it may helps so far.
