### ISSUE TITLE
[1.21.1} Golden Hopper crash on start

### ISSUE THREAD

**Issue by Periam** [MrCrayfish/GoldenHopper#37]
After adding the latest vrsion of the mod to MC 1.21.1 the same crash the game initiating.

neoforge-21.1.37
framework-neoforge-1.21.1-0.9.1
goldenhopper-neoforge-1.21.1-1.5.4
jei-1.21.1-neoforge-19.16.4.166
super factory manager-1.21.1-4.19.0

log
[Uploading crash-2024-09-04_11.27.25-client.txt…]()

**Comment by MrCrayfish** [comment]
You'll need to resend the log. You didn't wait for it to finish

**Comment by Periam** [comment]
Hello, here is the log again.
[crash-2024-09-05_08.45.54-client.txt](https://github.com/user-attachments/files/16892860/crash-2024-09-05_08.45.54-client.txt)

**Comment by MrCrayfish** [comment]
This should be fixed as of version `1.5.5`. The commit can be found here https://github.com/MrCrayfish/GoldenHopper/commit/66829e53ec75d311c529b50fb362ab9a6336a770
