### ISSUE TITLE
Please add NBT comparison for filter

### ISSUE THREAD

**Issue by koenigstag** [MrCrayfish/GoldenHopper#38]
Love you mod, and found that my use case requires an nbt comparison of item and filter.
Can you please add this to you Entity.canPlaceItem method?
Im using an 1.20.1 version, so asking to update this version with this feature.

**Comment by MrCrayfish** [comment]
Thank you for the suggestion, however this mod is feature complete. The only updates you will see are when it's ported to a new Minecraft version or fixing bugs. I can only suggest finding another mod that is suitable for your use case.
