### ISSUE TITLE
Crash on Startup with Goldenhopper v1.5.5

### ISSUE THREAD

**Issue by MiyuHimano** [MrCrayfish/GoldenHopper#39]
Hello!
I did a fresh install of minecraft 1.21.1 Fabric and wanted to try some mods.
The game crashed on start:

The game crashed whilst bootstrap
Error: java.lang.ExceptionInInitializerError

In the log it shows a problem with the hopper code (added)
Thanks in advance :)
[crash-2024-09-23_19.54.37-client.txt](https://github.com/user-attachments/files/17102179/crash-2024-09-23_19.54.37-client.txt)

**Comment by MrCrayfish** [comment]
Missing Framework https://www.curseforge.com/minecraft/mc-mods/framework
