### ISSUE TITLE
Game crashes when golden hopper inserts into tile entities from certain other mods. 

### ISSUE THREAD

**Issue by theaigcaman** [MrCrayfish/GoldenHopper#5]
The game crashes when using a golden hopper to insert items into tile entities from several other mods. The game crashed when attempting to insert anything into a barrel from Metal Barrels (https://www.curseforge.com/minecraft/mc-mods/metal-barrels) using a golden hopper, and also crashed when attempting to insert a disk into a Refined Storage disk drive. 
The specific error is 
```
The game crashed whilst ticking block entity
Error: java.lang.ClassCastException: com.raoulvdberge.refinedstorage.tile.DiskDriveTile cannot be cast to net.minecraft.inventory.IInventory
```

Here are crash logs for both. 
[crash-2020-04-20_15.52.55-server.txt](https://github.com/MrCrayfish/GoldenHopper/files/4506466/crash-2020-04-20_15.52.55-server.txt)
[crash-2020-04-20_16.00.59-server.txt](https://github.com/MrCrayfish/GoldenHopper/files/4506467/crash-2020-04-20_16.00.59-server.txt)

**Comment by theaigcaman** [comment]
It seem like items can be removed from the offending inventories using golden hoppers without issue. Golden hoppers are also able to insert items into machines from Silent's Mechanisms (https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms) without any apparent issue.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/GoldenHopper/commit/bbc2d9decf089e3dab69d9b715e3f36485ab5f30
